name: Build and test project
on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    format:
        runs-on: ubuntu-latest
        name: Check code formatting
        steps:
            - uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - run: yarn install
            - run: yarn run check-format
    build:
        runs-on: ubuntu-latest
        name: Build project
        steps:
            - uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - run: yarn install
            - run: yarn run build
    test:
        runs-on: ubuntu-latest
        name: Test project
        steps:
            - uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - run: yarn install
            - run: yarn run test
